version: "3.9"

services:
  backend:
    build: ./backend
    #container_name: registos-paroquiais
    restart: unless-stopped
    ports:
      - "8000:8000"       # Expor apenas na rede local; não abrir no router para a Internet
    volumes:
      - ./data:/data      # Base de dados persistente
      - ./frontend:/app/frontend:ro
    env_file:
      - .env
    environment:
      - DB_PATH=/data/registos.db
